### ISSUE TITLE
image teamatldocker/nginx is not available

### ISSUE THREAD

**Issue by luizmotta01** [teamatldocker/jira#144]
### Description

I'm developing an application that will receive webhooks from Jira. I need to get Jira running using HTTPS to set OAuth authentication, but following the steps described in README to get this done, I found that the image "teamatldocker/nginx" it's not available anymore in docker hub. 

### Steps to Reproduce

    *  Set environment variable JIRA_PROXY_NAME in docker-compose to 192.168.99.100
    *  Set environment variable JIRA_PROXY_PORT in docker-compose to 443
    *  Set environment variable JIRA_PROXY_SCHEME in docker-compose to https
    *  Create Nginx service in docker-compose with the provided variables in README.md

**Logs will put out** 
```bash
    5>Pulling nginx (teamatldocker/nginx:)...
    5>The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing
```

**docker-compose.yml**
```yml
version: "3.8"

services:
  jira:
    image: teamatldocker/jira
    container_name: jira
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - api
    environment:
      - JIRA_DATABASE_URL=postgresql://postgres@postgresql/jiradb
      - JIRA_DB_PASSWORD=<PASSWORD>
      - SETENV_JVM_MINIMUM_MEMORY=2048m
      - SETENV_JVM_MAXIMUM_MEMORY=4096m
      - JIRA_PROXY_NAME=192.168.99.100
      - JIRA_PROXY_PORT=443
      - JIRA_PROXY_SCHEME=https
      - DOCKER_WAIT_HOST=postgresql
      - DOCKER_WAIT_PORT=5432
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  nginx:
    image: teamatldocker/nginx
    container_name: nginx
    networks:
       - jiranet
    volumes:
      - nginxdata:/etc/nginx/templates
    ports:
       - "443:443"
    environment:
       - SERVER1REVERSE_PROXY_LOCATION1=/
       - SERVER1REVERSE_PROXY_PASS1=http://jira:8080
       - SERVER1CERTIFICATE_DNAME=/CN=CrustyClown/OU=SpringfieldEntertainment/O=crusty.springfield.com/L=Springfield/C=US
       - SERVER1HTTPS_ENABLED=true
       - SERVER1HTTP_ENABLED=false

  postgresql:
    image: postgres:9.5-alpine
    container_name: postgresql
    networks:
      - jiranet
    ports:
      - "5432:5432"
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<PASSWORD>
      - POSTGRES_DB=jiradb
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
  nginxdata:
    external: false

networks:
  jiranet:
    driver: bridge
```
